SELECT FH.FLAVOR AS FLAVOR FROM FIRST_HALF FH
JOIN (SELECT F.SHIPMENT_ID AS SHIPMENT_ID, SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) AS C FROM FIRST_HALF F
JOIN JULY J ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY C DESC
LIMIT 3
) S ON S.SHIPMENT_ID = FH.SHIPMENT_ID
