SELECT A.APNT_NO, P.PT_NAME, P.PT_NO, A.MCDP_CD, D.DR_NAME, A.APNT_YMD FROM PATIENT P 
JOIN (
    SELECT * FROM APPOINTMENT
WHERE YEAR(APNT_YMD) = 2022 AND MONTH(APNT_YMD) = 4 AND DAY(APNT_YMD) = 13 AND APNT_CNCL_YN = 'N'
) A
ON A.PT_NO = P.PT_NO
JOIN DOCTOR D
ON A.MDDR_ID = D.DR_ID
ORDER BY A.APNT_YMD ASC