SELECT E.EMP_NO, E.EMP_NAME, G.GRADE, (
E.SAL * (
    CASE WHEN G.GRADE = 'S' THEN 0.2
    WHEN G.GRADE = 'A' THEN 0.15
    WHEN G.GRADE = 'B' THEN 0.1
    ELSE 0 END
)
) AS BONUS FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO,
    (CASE WHEN AVG(SCORE) >= 96 THEN 'S'
    WHEN AVG(SCORE) >= 90 THEN 'A'
     WHEN AVG(SCORE) >= 80 THEN 'B'
     ELSE 'C' END
    ) GRADE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) G
ON G.EMP_NO = E.EMP_NO
ORDER BY E.EMP_NO ASC