SELECT M.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE FROM MEMBER_PROFILE M
JOIN REST_REVIEW RR
ON M.MEMBER_ID = RR.MEMBER_ID
JOIN (
    SELECT MEMBER_ID FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(MEMBER_ID) DESC
    LIMIT 1
) R
ON M.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE ASC, RR.REVIEW_TEXT ASC