SELECT II2.ITEM_ID, II2.ITEM_NAME, II2.RARITY 
FROM ITEM_INFO II1
JOIN ITEM_TREE IT
ON II1.ITEM_ID = IT.PARENT_ITEM_ID
JOIN ITEM_INFO II2
ON IT.ITEM_ID = II2.ITEM_ID
WHERE II1.RARITY = 'RARE'
ORDER BY II2.ITEM_ID DESC