SELECT COUNT(ID) AS FISH_COUNT, MAX(LENGTH) AS MAX_LENGTH, FISH_TYPE FROM FISH_INFO
WHERE CASE WHEN LENGTH IS NULL THEN 10
WHEN LENGTH THEN LENGTH
END
GROUP BY FISH_TYPE
HAVING AVG(LENGTH) >= 33
ORDER BY FISH_TYPE ASC